### ISSUE TITLE
How can I train a model ?

### ISSUE THREAD

**Issue by journeytosilius** [asigalov61/tegridy-tools#1]
Hi, I come here because the author of this repo : https://github.com/asigalov61/Optimus-VIRTUOSO/blob/main/optimus_virtuoso_composer.py

is not online anymore, and I'm trying to fork his code to experiment further, but I don't know how to train a model or what kind of format do I need to use ( as in MIDI files ) to train new models. for now I have adapted these functions to work locally but I need to know how to create a dataset that is usable ( I'm new to ML )  Would you please guide me a little / give some direction so I can proceed ? 

Thank you very much

**Comment by asigalov61** [comment]
@chromafunk Please write me at my GitHub email asigalov61@hotmail.com

I would be happy to help :)

Sorry about missed messages.

Alex
